name: S3 Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'exampleSite/**'
      - '.github/workflows/deploy.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Hugo
          uses: peaceiris/actions-hugo@v2
          with:
            hugo-version: 'latest'
        - name: Install AWS CLI
          run: |
            sudo apt-get install -y python3-pip
            pip3 install awscli
        - name: Build Hugo site
          run: hugo --minify
        - name: Upload files to S3
          run: aws s3 sync app/public/ s3://${{ env.BUCKET_NAME }}/blog --exact-timestamps --delete