name: S3 Deploy

on:
  workflow_dispatch:
  push:
    paths:
      - 'exampleSite/**'
      - '.github/workflows/deploy.yml'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      HUGO_VERSION: 0.134.2
    steps:
        - name: Install Hugo CLI
          run: |
            wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
            && sudo dpkg -i ${{ runner.temp }}/hugo.deb 
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            submodules: recursive
            fetch-depth: 0
        - name: Install AWS CLI
          run: |
            sudo apt-get install -y python3-pip
            pip3 install awscli
        - name: Build with Hugo
          env:
            HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
            HUGO_ENVIRONMENT: production
            TZ: America/Los_Angeles
          run: |
            hugo \
                --gc \
                --minify \
                --baseURL "https://ngon.info/"
        - name: Upload files to S3
          run: aws s3 sync app/public/ s3://${{ env.BUCKET_NAME }}/blog --exact-timestamps --delete